import {NgModule} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatInputModule,
  MatDividerModule,
  MatSnackBarModule,
  MatTabsModule,
  MatDatepickerModule,
  MatButtonToggleModule,
  MatRadioModule,
  MatSortModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatTableModule,
  MatPaginatorModule,
  MatCardModule,
  MatOptionModule,
  MatSelectModule,
  MatButtonModule,
  MatNativeDateModule,
  MatIconModule,
  MatSidenavModule,
  MatListModule,
  MatToolbarModule,
  MatExpansionModule,
  MatMenuModule,
  MatStepperModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatInputModule,
    MatDividerModule,
    MatSnackBarModule,
    MatTabsModule,
    MatDatepickerModule,
    MatButtonToggleModule,
    MatRadioModule,
    MatSortModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatTableModule,
    MatPaginatorModule,
    MatCardModule,
    MatOptionModule,
    MatSelectModule,
    MatButtonModule,
    MatToolbarModule,
    MatNativeDateModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatExpansionModule,
    MatMenuModule,
    MatStepperModule
  ],
  exports: [
    CommonModule,
    MatInputModule,
    MatDividerModule,
    MatSnackBarModule,
    MatTabsModule,
    MatDatepickerModule,
    MatButtonToggleModule,
    MatRadioModule,
    MatSortModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatTableModule,
    MatPaginatorModule,
    MatCardModule,
    MatOptionModule,
    MatSelectModule,
    MatButtonModule,
    MatToolbarModule,
    MatNativeDateModule,
    MatIconModule,
    MatSidenavModule,
    MatListModule,
    MatExpansionModule,
    MatMenuModule,
    MatStepperModule
  ],
})
export class CustomMaterialModule { }
